In [11]:
import pandas as pd
import re as re

In [7]:
df = pd.read_csv('/content/IMDB Dataset.csv' , on_bad_lines  = 'skip' )

In [8]:
df.size

100000

In [17]:
df

,review,sentiment,text
0,One of the other reviewers has mentioned that ...,positive,One of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,positive,A wonderful little production. The filming tec...
2,I thought this was a wonderful way to spend ti...,positive,I thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,negative,Basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"Petter Mattei's ""Love in the Time of Money"" is..."
...,...,...,...
49995,I thought this movie did a down right good job...,positive,I thought this movie did a down right good job...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,"Bad plot, bad dialogue, bad acting, idiotic di..."
49997,I am a Catholic taught in parochial elementary...,negative,I am a Catholic taught in parochial elementary...
49998,I'm going to have to disagree with the previou...,negative,I'm going to have to disagree with the previou...
49999,No one expects the Star Trek movies to be high...,negative,No one expects the Star Trek movies to be high...

In [14]:
def remove_tags(string):
    result = re.sub('<.*?>','',string)
    return result

In [16]:
df['text']=df['review'].apply(lambda cw : remove_tags(cw))

In [18]:
df = df.drop('review' , axis = 1)

In [19]:
df.head()

  sentiment                                               text
0  positive  One of the other reviewers has mentioned that ...
1  positive  A wonderful little production. The filming tec...
2  positive  I thought this was a wonderful way to spend ti...
3  negative  Basically there's a family where a little boy ...
4  positive  Petter Mattei's "Love in the Time of Money" is...

In [22]:
df.to_csv('/content/IMDB Dataset_Fixed.csv')

In [23]:
df

      sentiment                                               text
0      positive  One of the other reviewers has mentioned that ...
1      positive  A wonderful little production. The filming tec...
2      positive  I thought this was a wonderful way to spend ti...
3      negative  Basically there's a family where a little boy ...
4      positive  Petter Mattei's "Love in the Time of Money" is...
...         ...                                                ...
49995  positive  I thought this movie did a down right good job...
49996  negative  Bad plot, bad dialogue, bad acting, idiotic di...
49997  negative  I am a Catholic taught in parochial elementary...
49998  negative  I'm going to have to disagree with the previou...
49999  negative  No one expects the Star Trek movies to be high...

[50000 rows x 2 columns]